# Generated by Django 3.1.1 on 2020-09-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20200926_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('google_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Main content',
                'verbose_name_plural': 'Main content',
            },
        ),
        migrations.CreateModel(
            name='MainFrameContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='about/maincontent')),
            ],
            options={
                'verbose_name': 'Main content',
                'verbose_name_plural': 'Main content',
            },
        ),
    ]
