# Generated by Django 3.1.1 on 2020-09-28 10:59

import aboutus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20200928_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='image',
            field=models.ImageField(upload_to='about/company', validators=[aboutus.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(upload_to='about/team', validators=[aboutus.models.validate_image]),
        ),
    ]
