# Generated by Django 3.1.1 on 2020-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselLatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='home/carousel_latest/')),
            ],
        ),
        migrations.CreateModel(
            name='CarouselTrending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='home/carousel_trending')),
            ],
        ),
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='home/our_product')),
            ],
        ),
    ]
