# Generated by Django 3.1.1 on 2020-09-28 10:59

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact forms',
            },
        ),
        migrations.AlterField(
            model_name='carousellatest',
            name='image',
            field=models.ImageField(upload_to='home/carousel_latest/', validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='carouseltrending',
            name='image',
            field=models.ImageField(upload_to='home/carousel_trending', validators=[home.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='image',
            field=models.ImageField(upload_to='home/our_product', validators=[home.models.validate_image]),
        ),
    ]
