# Generated by Django 3.1.1 on 2020-10-04 08:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200928_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='home/carousel_latest/', validators=[home.models.validate_image])),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselLatest',
        ),
        migrations.DeleteModel(
            name='CarouselTrending',
        ),
    ]
