# Generated by Django 3.1.1 on 2020-09-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200926_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_selling',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
