# Generated by Django 3.1.1 on 2020-09-28 05:54

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200926_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='best_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_location_product, validators=[products.models.validate_image]),
        ),
    ]
