# Generated by Django 3.1.1 on 2020-09-28 10:59

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200928_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_location, validators=[products.models.validate_image]),
        ),
    ]
