# Generated by Django 3.1.1 on 2020-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200928_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='latest_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_product',
            field=models.BooleanField(default=False),
        ),
    ]
